[package]
name = "mkmetadata"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
flate2 = "1.0.25"
governor = "0.5.1"
musicbrainz_rs = "0.4.0"
open-library = "0.7.1"
rand = "0.8.5"
reqwest = { version = "0.11.13", default-features = false, features = [
    "json",
    "native-tls",
] }
roxmltree = "0.17.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.2", features = [
    "chrono",
    "json",
    "runtime-tokio-rustls",
    "postgres",
    "uuid",
] }
stdext = "0.3.1"
substring = "1.4.5"
sys-info = "0.9.1"
tar = "0.4.38"
tokio = { version = "1.24.1", features = ["full"] }
torrent-name-parser = "0.11.0"
urlencoding = "2.1.2"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
md-5 = "0.10.5"
sha-1 = "0.10.1"

[dev-dependencies]
tokio-test = "*"
