[package]
name = "mkmetadata"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
chrono = "0.4"
flate2 = "1.0.20"
governor = "0.3.2"
pyo3 = { version = "0.14.3" }
pyo3-asyncio = { version = "0.14", features = ["attributes", "tokio-runtime"] }
reqwest = { version = "0.11.3", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sqlx = { version = "0.5.6", features = [ "chrono", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.4.0"
tar = "0.4.37"
tokio = { version = "1.6.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[dev-dependencies]
tokio-test = "*"