[package]
name = "mkmetadata"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
flate2 = "1.0.22"
governor = "0.4.2"
rand = "0.8.5"
reqwest = { version = "0.11.10", default-features = false, features = ["json", "rustls-tls"] }
roxmltree = "0.14.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
sqlx = { version = "0.5.13", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
substring = "1.4.5"
sys-info = "0.9.1"
tar = "0.4.38"
tokio = { version = "1.18.2", features = ["full"] }
torrent-name-parser = "0.11.0"
uuid = { version = "1.1.0", features = ["serde", "v4"] }
md-5 = "0.10.1"
sha-1 = "0.10.0"

rocket_dyn_templates = { git = "https://github.com/SergioBenitez/Rocket/", features = ["tera"]}

[dev-dependencies]
tokio-test = "*"