[package]
name = "mktestsharereaddb"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
argh = "0.1.7"
chrono = { version = "0.4.24", features = ["serde"] }
env_logger = "^0.10"
mk_lib_common = { path = "../../src/mk_lib_common" }
mk_lib_database = { path = "../../src/mk_lib_database" }
mk_lib_file = { path = "../../src/mk_lib_file", features = ["smb"] }
mk_lib_network = { path = "../../src/mk_lib_network" }
pavao = "0.2.3"
reqwest = { version = "0.11.17", default-features = false, features = [
    "json",
    "rustls-tls",
] }
rpassword = "7.2"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["full"] }
walkdir = "2.3.3"

[dev-dependencies]
tokio-test = "*"
