[package]
name = "mkschedulesdirectupdate"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
chrono = "0.4"
reqwest = { version = "0.11.4", default-features = false, features = ["json", "rustls-tls"] }
rustls = "0.19.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sqlx = { version = "0.5.7", features = [ "chrono", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.9.0"
tokio = { version = "1.6.0", features = ["full"] }
tokio-rustls = "0.22.0"
validator = { version = "0.14", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"