[package]
name = "mkschedulesdirectupdate"
version = "0.0.1"
edition = "2021"

[profile.dev]
panic = 'unwind'
strip = "none"
lto = false
codegen-units = 16

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_database = { path = "mk_lib_database" }
mk_lib_rabbitmq = { path = "mk_lib_rabbitmq" }

chrono = { version = "0.4.33", features = ["serde"] }
reqwest = { version = "0.11.24", default-features = false, features = [
    "json",
    "native-tls",
] }
rustls = "0.22.2"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.36.0", features = ["full"] }
tokio-rustls = "0.25.0"
uuid = { version = "1.7.0", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"
