[package]
name = "mkschedulesdirectupdate"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
mk_lib_database = { path = "mk_lib_database" }
mk_lib_logging = { path = "mk_lib_logging" }
reqwest = { version = "0.11.18", default-features = false, features = ["json", "native-tls"] }
rustls = "0.20.8"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.28.2", features = ["full"] }
tokio-rustls = "0.23.4"
uuid = { version = "1.3.3", features = ["serde", "v4"] }
validator = { version = "0.15.0", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"
