[package]
name = "mkschedulesdirectupdate"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
reqwest = { version = "0.11.13", default-features = false, features = ["json", "native-tls"] }
rustls = "0.20.6"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.3", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.24.1", features = ["full"] }
tokio-rustls = "0.23.2"
urlencoding = "2.1.2"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
validator = { version = "0.15.0", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"