[package]
name = "mkschedulesdirectupdate"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
reqwest = { version = "0.11.10", default-features = false, features = ["json", "rustls-tls"] }
rustls = "0.20.2"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sqlx = { version = "0.5.11", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.9.1"
tokio = { version = "1.17.0", features = ["full"] }
tokio-rustls = "0.23.2"
validator = { version = "0.14", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"