[package]
name = "myapp"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
async-std = "1.9.0"
chrono = "0.4"
flate2 = "1.0.20"
reqwest = { version = "0.11.4", default-features = false, features = ["json", "rustls-tls"] }
roxmltree = "0.14.1"
rustls = "0.19.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sqlx = { version = "0.5.7", features = [ "chrono", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.4.0"
tar = "0.4.37"
tokio = { version = "1.6.0", features = ["full"] }
#xmlparser = "0.13.3"

[dev-dependencies]
tokio-test = "*"