[package]
name = "mkmetadatamame"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
async-std = "1.9.0"
chrono = "0.4.19"
flate2 = "1.0.20"
reqwest = { version = "0.11.4", default-features = false, features = ["json", "rustls-tls"] }
roxmltree = "0.14.1"
rustls = "0.20.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sqlx = { version = "0.5.9", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.9.0"
tar = "0.4.37"
tokio = { version = "1.12.0", features = ["full"] }
#xmlparser = "0.13.3"
walkdir = "2.3.2"
zip = "0.5.13"

[dev-dependencies]
tokio-test = "*"