[package]
name = "mkmetadatamame"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
async-std = "1.10.0"
chrono = { version = "0.4.23", features = ["serde"] }
flate2 = "1.0.25"
quickxml_to_serde = { version = "0.5.0", features = ["json_types"] }
reqwest = { version = "0.11.13", default-features = false, features = ["json", "native-tls"] }
rustls = "0.20.7"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.2", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
stdext = "0.3.1"
sys-info = "0.9.1"
tar = "0.4.38"
tokio = { version = "1.24.1", features = ["full"] }
walkdir = "2.3.2"
urlencoding = "2.1.2"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
zip = "0.6.2"

[dev-dependencies]
tokio-test = "*"