[package]
name = "mkmulticast"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
# 0.31.0 breaks datalink
pnet = "0.30.0"
#lazy_static = "1.4.0"
shiplift = { version = "0.7", default-features = false, features = [
    "unix-socket",
] }
socket2 = { version = "0.4.7", features = ["all"] }
#socket2 = { version = "0.4.7", features = ["reuseport"] }
tokio = { version = "1.21.2", features = ["full"] }

[dev-dependencies]
tokio-test = "*"
