[package]
name = "mkdownload"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"

[dependencies]
amiquip = { version = "0.4.2", default-features = false }
chrono = "0.4.19"
reqwest = { version = "0.11.9", default-features = false, features = ["json", "rustls-tls"] }
rustube = "0.3.8"   # this is adding openssl to hyper - due to cargo.toml of "default" request settings
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
sqlx = { version = "0.5.10", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.9.1"
tokio = { version = "1.17.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
validator = { version = "0.14", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"