[package]
name = "mkdownload"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
amiquip = { version = "0.4", default-features = false }
chrono = "0.4"
reqwest = { version = "0.11.3", default-features = false, features = ["json", "rustls-tls"] }
#rustube = "0.3.5"    # this is adding openssl to hyper - due to cargo.toml of "default" request settings
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sqlx = { version = "0.5.7", features = [ "chrono", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.4.0"
tokio = { version = "1.6.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
validator = { version = "0.14", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"