[package]
name = "mkdownload"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amiquip = { version = "0.4.2", default-features = false }
chrono = { version = "0.4.24", features = ["serde"] }
governor = "0.5.1"
mk_lib_database = { path = "mk_lib_database" }
mk_lib_logging = { path = "mk_lib_logging" }
mk_lib_network = { path = "mk_lib_network" }
reqwest = { version = "0.11.18", default-features = false, features = [
    "json",
    "native-tls",
] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.28.2", features = ["full"] }
uuid = { version = "1.3.3", features = ["serde", "v4"] }
validator = { version = "0.16.0", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"
