[package]
name = "mkwebapp"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
amiquip = { version = "0.4", default-features = false }
chrono = "0.4"
lazy_static = "1.4.0"
rcgen = "0.8.11"
reqwest = { version = "0.11.3", default-features = false, features = ["json", "rustls-tls"] }
ring = "0.16.20"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
shiplift = { version = "0.7", default-features = false, features = ["unix-socket"] }
sqlx = { version = "0.5.6", features = [ "chrono", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.4.0"
tera = "1.12.1"
tokio = { version = "1.6.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
walkdir = "2.3.2"

rocket = { git = "https://github.com/SergioBenitez/Rocket/", features = ["json", "secrets"]}
rocket_dyn_templates = { git = "https://github.com/SergioBenitez/Rocket/", features = ["tera"]}

[dev-dependencies]
tokio-test = "*"