[package]
name = "mkwebapp"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amiquip = { version = "0.4.2", default-features = false }
chrono = { version = "0.4.19", features = ["serde"] }
docker-api = { version = "0.12.1", features = ["swarm"] }
lazy_static = "1.4.0"
libc = "0.2.126"
num-format = { version = "0.4.4", features = ["with-system-locale"] }
paginator = "0.2.3"
rcgen = "0.10.0"
reqwest = { version = "0.11.13", default-features = false, features = [
    "json",
    "native-tls",
] }
ring = "0.16.20"
rocket_auth = { version = "0.4.0", features = ["sqlx-postgres"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
sqlx = { version = "0.5.13", features = [
    "chrono",
    "json",
    "runtime-tokio-rustls",
    "postgres",
    "uuid",
] }
stdext = "0.3.1"
sys-info = "0.9.1"
tera = "1.15.0"
tokio = { version = "1.18.2", features = ["full"] }
urlencoding = "2.1.2"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
walkdir = "2.3.2"

rocket = { version = "0.5.0-rc.2", features = ["json", "secrets", "uuid"] }
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }

[dev-dependencies]
tokio-test = "*"
