[package]
name = "mkwebapp"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amiquip = { version = "0.4.2", default-features = false }
chrono = { version = "0.4.19", features = ["serde"] }
lazy_static = "1.4.0"
paginator = "0.2.3"
rcgen = "0.9.2"
reqwest = { version = "0.11.10", default-features = false, features = ["json", "rustls-tls"] }
ring = "0.16.20"
rocket_auth = { version = "0.4.0", features = ["sqlx-postgres"] }
# rocket_csrf = "0.3.0" - requires nightly
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
shiplift = { version = "0.7", default-features = false, features = ["unix-socket"] }
sqlx = { version = "0.5.13", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.9.1"
tera = "1.15.0"
tokio = { version = "1.18.2", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
walkdir = "2.3.2"

rocket = { version = "0.5.0-rc.2", features = ["json", "secrets", "uuid"]}
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"]}

[dev-dependencies]
tokio-test = "*"
