[default]
template_dir = "templates"
address = "0.0.0.0"
port = 8080
workers = 10
keep_alive = 5
# openssl rand -base64 32
secret_key = "UOx4cuTYUlhBlvmuLuOrf4qTWJXnJMG3Z3Es4VxG3nI="
#limits = { forms = 32768 }
limits.data-form = "2MiB"