[package]
name = "mktcpserver"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"

[dependencies]
argh = "0.1.6"
amiquip = { version = "0.4.2", default-features = false }
chrono = { version = "0.4.19", features = ["serde"] }
rustls = "0.20.2"
rustls-pemfile = "0.2.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sqlx = { version = "0.5.11", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.9.1"
tokio = { version = "1.17.0", features = ["full"] }
tokio-rustls = "0.23.2"
validator = { version = "0.14", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"