[package]
name = "mk_lib_file"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
aws-config = { version = "0.56.0", optional = true }
aws-sdk-s3= { version = "0.29.0", optional = true }
serde_json = "1.0.96"
stdext = "0.3.1"
tokio = { version = "1.28.2", features = ["full"] }
walkdir = "2.3.3"

[features]
s3 = ["dep:aws-config", "dep:aws-sdk-s3"]

[dev-dependencies]
tokio-test = "*"
