[package]
name = "mk_lib_file"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_logging = { path = "/root/MediaKraken/src/mk_lib_logging" }
serde_json = "1.0.96"
stdext = "0.3.1"
tokio = { version = "1.28.1", features = ["full"] }
walkdir = "2.3.3"

[dev-dependencies]
tokio-test = "*"
