[package]
name = "mkhardwarecontrol"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
amiquip = { version = "0.4", default-features = false }
chrono = "0.4"
reqwest = { version = "0.11.3", default-features = false, features = ["json", "rustls-tls"] }
rppal = { version = "0.12.0", features = ["hal"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sys-info = "0.9.0"
tokio = { version = "1.6.0", features = ["full"] }

[dev-dependencies]
tokio-test = "*"