[package]
name = "mkhardwarecontrol"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amiquip = { version = "0.4.2", default-features = false }
chrono = { version = "0.4.23", features = ["serde"] }
mini-telnet = "0.1.8"
reqwest = { version = "0.11.13", default-features = false, features = ["json", "rustls-tls"] }
rppal = { version = "0.13.1", features = ["hal"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serialport = "4.1.0"
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.24.1", features = ["full"] }

[dev-dependencies]
tokio-test = "*"