[package]
name = "mkhardwarecontrol"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
amiquip = { version = "0.4", default-features = false }
chrono = "0.4.19"
reqwest = { version = "0.11.6", default-features = false, features = ["json", "rustls-tls"] }
rppal = { version = "0.13.0", features = ["hal"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sys-info = "0.9.1"
tokio = { version = "1.13.0", features = ["full"] }

[dev-dependencies]
tokio-test = "*"