[package]
name = "mkgamesdbnetfetchbulk"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_database = { path = "/root/MediaKraken/src/mk_lib_database" }
mk_lib_logging = { path = "/root/MediaKraken/src/mk_lib_logging" }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["full"] }

[dev-dependencies]
tokio-test = "*"
