[package]
name = "mkmediascanner"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_common = { path = "mk_lib_common" }
mk_lib_database = { path = "mk_lib_database" }
mk_lib_file = { path = "mk_lib_file", features = [ "smb" ] }
mk_lib_rabbitmq = { path = "mk_lib_rabbitmq" }

chrono = { version = "0.4.33", features = ["serde"] }
fancy-regex = "0.13.0"
lazy_static = "1.4.0"
num-format = "0.4.4"
reqwest = { version = "0.11.24", default-features = false, features = [
    "json",
    "rustls-tls",
] }
rustls = "0.22.2"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.36.0", features = ["full"] }
uuid = { version = "1.7.0", features = ["serde", "v4"] }
walkdir = "2.4.0"

[dev-dependencies]
tokio-test = "*"
