[package]
name = "mkmediascanner"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"

[dependencies]
amiquip = { version = "0.4.2", default-features = false }
async-std = "1.10.0"
chrono = "0.4.19"
num-format = "0.4.0"
regex = "1.5.4"
reqwest = { version = "0.11.9", default-features = false, features = ["json", "rustls-tls"] }
rustls = "0.20.2"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
sqlx = { version = "0.5.10", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.9.1"
tokio = { version = "1.15.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
walkdir = "2.3.2"

[dev-dependencies]
tokio-test = "*"