[package]
name = "mkhardwarescanner"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_database = { path = "mk_lib_database" }
mk_lib_hardware = { path = "mk_lib_hardware" }
mk_lib_network = { path = "mk_lib_network" }
mk_lib_rabbitmq = { path = "mk_lib_rabbitmq" }

chrono = { version = "0.4.31", features = ["serde"] }
crab-dlna = "0.2.1"
futures-util = "0.3.30"
huelib = "0.13.2" # https://github.com/nn1ks/huelib-rs
mdns = "3.0.0"
reqwest = { version = "0.11.23", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
sonor = "2.0.0"
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.35.1", features = ["full"] }

[dev-dependencies]
tokio-test = "*"
