[package]
name = "mkhardwarescanner"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
crab-dlna = "0.1.0"
futures-util = "0.3.28"
huelib = "0.13.2" # https://github.com/nn1ks/huelib-rs
mdns = "3.0.0"
mk_lib_database = { path = "../../../src/mk_lib_database" }
mk_lib_hardware = { path = "../../../src/mk_lib_hardware" }
mk_lib_network = { path = "../../../src/mk_lib_network" }
mk_lib_rabbitmq = { path = "../../../src/mk_lib_rabbitmq" }
reqwest = { version = "0.11.18", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
sonor = "1.1.0"
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.28.2", features = ["full"] }

[dev-dependencies]
tokio-test = "*"
