[package]
name = "mkwebapp"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amiquip = { version = "0.4.2", default-features = false }
askama = { version = "0.12.0", features = ["with-axum", "mime", "mime_guess"] }
askama_axum = "0.3.0"
askama-filters = "0.1.3"
axum = { version = "0.6.11", features = ["http2", "json", "ws"] }
axum-extra = "0.7.2"
axum_static = "1.2.1"
bytesize = {version = "1.1.0", features = ["serde"]}
chrono = { version = "0.4.23", features = ["serde"] }
docker-api = { version = "0.12.1", features = ["swarm"] }
lazy_static = "1.4.0"
libc = "0.2.126"
num-format = { version = "0.4.4", features = ["with-system-locale"] }
paginator = "0.2.3"
rcgen = "0.10.0"
reqwest = { version = "0.11.13", default-features = false, features = [
    "json",
    "native-tls",
] }
ring = "0.16.20"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.2", features = [
    "chrono",
    "json",
    "runtime-tokio-rustls",
    "postgres",
    "uuid",
] }
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.24.1", features = ["full"] }
tower = { version = "0.4.13" }
tower-http = { version = "0.4.0", features = ["normalize-path"] }
transmission-rpc = "0.4.0"
urlencoding = "2.1.2"
uuid = { version = "1.3.0", features = ["serde", "v4"] }
validator = { version = "0.16.0", features = ["derive"] }
walkdir = "2.3.2"

[dev-dependencies]
tokio-test = "*"
