[package]
name = "mkwebapp"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amiquip = { version = "0.4.2", default-features = false }
askama = { version = "0.12.0", features = ["with-axum", "mime", "mime_guess"] }
askama_axum = "0.3.0"
askama-filters = "0.1.3"
axum = { version = "0.6.18", features = ["form", "http2", "json", "ws"] }
axum_csrf = "0.6.2"
axum-extra = "0.7.4"
axum-flash = "0.7.0"
axum-handle-error-extract = "0.1.0"
axum-prometheus = "0.3.3"
axum_session = { version = "0.2.3", features = [ "postgres-rustls"] }
axum_session_auth = { version = "0.2.1", features = [ "postgres-rustls" ] }
axum_static = "1.2.1"
bytesize = {version = "1.2.0", features = ["serde"]}
chrono = { version = "0.4.24", features = ["serde"] }
docker-api = { version = "0.13.0", features = ["swarm"] }
futures = "0.3.28"
ipnetwork = "0.20.0"
lazy_static = "1.4.0"
libc = "0.2.144"
mk_lib_common = { path = "/root/MediaKraken/src/mk_lib_common" }
mk_lib_database = { path = "/root/MediaKraken/src/mk_lib_database" }
mk_lib_logging = { path = "/root/MediaKraken/src/mk_lib_logging" }
mk_lib_metadata = { path = "/root/MediaKraken/src/mk_lib_metadata" }
mk_lib_network = { path = "/root/MediaKraken/src/mk_lib_network" }
num-format = { version = "0.4.4", features = ["with-system-locale"] }
paginator = "0.2.6"
rcgen = "0.10.0"
reqwest = { version = "0.11.18", default-features = false, features = [
    "json",
    "native-tls",
] }
ring = "0.16.20"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
sqlx = { version = "0.6.3", features = [
    "chrono",
    "ipnetwork",
    "json",
    "runtime-tokio-rustls",
    "postgres",
    "uuid",
] }
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.28.2", features = ["full"] }
tower = { version = "0.4.13", features = ["retry", "timeout"] }
transmission-rpc = "0.4.1"
uuid = { version = "1.3.3", features = ["serde", "v4"] }
validator = { version = "0.16.0", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"
