[package]
name = "mkwebapp"
version = "0.0.1"
edition = "2021"

[profile.dev]
panic = 'unwind'
strip = "none"
lto = false
codegen-units = 16

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_common = { version = "0.0.1", registry = "kellnr" }
mk_lib_database = { version = "0.0.4", registry = "kellnr" }
mk_lib_file = { version = "0.0.1", registry = "kellnr" }
mk_lib_network = { version = "0.0.1", registry = "kellnr" }
mk_lib_rabbitmq = { version = "0.0.1", registry = "kellnr" }

askama = { version = "0.12.1", features = ["with-axum", "mime", "mime_guess"] }
askama_axum = "0.4.0"
askama-filters = "0.1.3"
axum = { version = "0.7.4", features = ["form", "http2", "json", "ws"] }
axum-client-ip = "0.5.0"
axum_csrf = "0.9.0"
axum-extra = "0.9.2"
axum-flash = "0.8.0"
axum-handle-error-extract = "0.1.0"
axum-prometheus = "0.6.1"
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
axum_session = { version = "0.12.4", features = [
    "postgres-rustls",
    "redis-db",
] }
axum_session_auth = { version = "0.12.1", features = [
    "postgres-rustls",
    "redis-db",
] }
bytesize = { version = "1.3.0", features = ["serde"] }
chrono = { version = "0.4.34", features = ["serde"] }
docker-api = { version = "0.14.0", features = ["swarm"] }
futures = "0.3.30"
hyper = { version = "1.2.0", features = ["full"] }
hyper-util = { version = "0.1.3", features = ["client-legacy"] }
ipnetwork = "0.20.0"
lazy_static = "1.4.0"
libc = "0.2.153"
num-format = { version = "0.4.4", features = ["with-system-locale"] }
paginator = "0.2.6"
rcgen = "0.12.1"
redis_pool = "0.3.0"
redis = { version = "0.24.0" }
reqwest = { version = "0.11.24", default-features = false, features = [
    "json",
    "native-tls",
] }
ring = "0.17.8"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
sqlx = { version = "0.7.3", features = [
    "chrono",
    "ipnetwork",
    "json",
    "runtime-tokio",
    "postgres",
    "uuid",
] }
stdext = "0.3.2"
sys-info = "0.9.1"
tokio = { version = "1.36.0", features = ["full"] }
tower = { version = "0.4.13", features = ["retry", "timeout", "util"] }
tower-http = { version = "0.5.2", features = ["fs"] }
transmission-rpc = "0.4.2"
uuid = { version = "1.7.0", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive"] }


[dev-dependencies]
tokio-test = "*"
