[package]
name = "mkwebapp"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_common = { path = "mk_lib_common" }
mk_lib_database = { path = "mk_lib_database" }
mk_lib_file = { path = "mk_lib_file", features = ["smb"] }
mk_lib_network = { path = "mk_lib_network" }
mk_lib_rabbitmq = { path = "mk_lib_rabbitmq" }

askama = { version = "0.12.1", features = ["with-axum", "mime", "mime_guess"] }
askama_axum = "0.4.0"
askama-filters = "0.1.3"
axum = { version = "0.7.3", features = ["form", "http2", "json", "ws"] }
axum-client-ip = "0.5.0"
axum_csrf = "0.9.0"
axum-extra = "0.9.1"
axum-flash = "0.8.0"
axum-handle-error-extract = "0.1.0"
axum-prometheus = "0.5.0"
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
axum_session = { version = "0.11.1", features = [
    "postgres-rustls",
    "redis-db",
] }
axum_session_auth = { version = "0.11.0", features = [
    "postgres-rustls",
    "redis-db",
] }
axum_static = "1.2.3"
bytesize = { version = "1.3.0", features = ["serde"] }
chrono = { version = "0.4.31", features = ["serde"] }
docker-api = { version = "0.14.0", features = ["swarm"] }
futures = "0.3.30"
ipnetwork = "0.20.0"
lazy_static = "1.4.0"
libc = "0.2.151"
num-format = { version = "0.4.4", features = ["with-system-locale"] }
paginator = "0.2.6"
rcgen = "0.12.0"
redis = "0.24.0"
reqwest = { version = "0.11.23", default-features = false, features = [
    "json",
    "native-tls",
] }
ring = "0.17.7"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
sqlx = { version = "0.7.3", features = [
    "chrono",
    "ipnetwork",
    "json",
    "runtime-tokio",
    "postgres",
    "uuid",
] }
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.35.1", features = ["full"] }
tower = { version = "0.4.13", features = ["retry", "timeout"] }
transmission-rpc = "0.4.2"
uuid = { version = "1.6.1", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive"] }


[dev-dependencies]
tokio-test = "*"
