[package]
name = "mktmdbnetfetchbulk"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
flate2 = "1.0.22"
reqwest = { version = "0.11.9", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sqlx = { version = "0.5.11", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.9.1"
tar = "0.4.38"
tokio = { version = "1.17.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
zip = "0.5.13"

rocket_dyn_templates = { git = "https://github.com/SergioBenitez/Rocket/", features = ["tera"]}

[dev-dependencies]
tokio-test = "*"