[package]
name = "mktmdbnetfetchbulk"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_common = { path = "../../../src/mk_lib_common" }
mk_lib_compression = { path = "../../../src/mk_lib_compression" }
mk_lib_database = { path = "../../../src/mk_lib_database" }
mk_lib_network = { path = "../../../src/mk_lib_network" }
mk_lib_rabbitmq = { path = "../../../src/mk_lib_rabbitmq" }

chrono = { version = "0.4.33", features = ["serde"] }
flate2 = "1.0.28"
reqwest = { version = "0.11.24", default-features = false, features = [
    "json",
    "native-tls",
] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
stdext = "0.3.1"
sys-info = "0.9.1"
tar = "0.4.40"
tokio = { version = "1.36.0", features = ["full"] }
uuid = { version = "1.7.0", features = ["serde", "v4"] }
zip = "0.6.6"

[dev-dependencies]
tokio-test = "*"
