[package]
name = "mkglobalcache"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_database = { path = "mk_lib_database" }
mk_lib_network = { path = "mk_lib_network" }
# do not use rust-tls below as it's incompatible with globalcache website
#reqwest = { version = "0.11.18", default-features = false, features = ["json", "native-tls"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
#sqlx = { version = "0.6.3", features = [ "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
#sys-info = "0.9.1"
tokio = { version = "1.28.2", features = ["full"] }
#uuid = { version = "1.3.3", features = ["serde", "v4"] }

[dev-dependencies]
tokio-test = "*"
