[package]
name = "mkmetadata"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"

[dependencies]
torrent-name-parser = "0.10.2"

[dev-dependencies]
tokio-test = "*"