[package]
name = "mkrabbitconsume"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
amiquip = { version = "0.4", default-features = false }
chrono = "0.4.19"
reqwest = { version = "0.11.6", default-features = false, features = ["json", "rustls-tls"] }
rustls = "0.20.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sqlx = { version = "0.5.9", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.9.1"
tokio = { version = "1.13.0", features = ["full"] }
validator = { version = "0.14", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"