[package]
name = "mkrabbitconsume"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
mk_lib_database = { path = "mk_lib_database" }
mk_lib_network = { path = "mk_lib_network" }
mk_lib_rabbitmq = { path = "mk_lib_rabbitmq" }

chrono = { version = "0.4.31", features = ["serde"] }
reqwest = { version = "0.11.23", default-features = false, features = [
    "json",
    "rustls-tls",
] }
rustls = "0.22.1"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.35.1", features = ["full"] }
uuid = { version = "1.6.1", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive"] }

[dev-dependencies]
tokio-test = "*"
