[package]
name = "mktmdbnetfetchupdate"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
chrono = "0.4.19"
flate2 = "1.0.22"
reqwest = { version = "0.11.6", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sys-info = "0.9.1"
sqlx = { version = "0.5.9", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
tar = "0.4.37"
tokio = { version = "1.13.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
zip = "0.5.13"

[dev-dependencies]
tokio-test = "*"