[package]
name = "mktmdbnetfetchupdate"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
flate2 = "1.0.26"
mk_lib_database = { path = "/root/MediaKraken/src/mk_lib_database" }
mk_lib_logging = { path = "/root/MediaKraken/src/mk_lib_logging" }
reqwest = { version = "0.11.17", default-features = false, features = ["json", "native-tls"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
sys-info = "0.9.1"
stdext = "0.3.1"
tar = "0.4.38"
tokio = { version = "1.28.0", features = ["full"] }
uuid = { version = "1.3.2", features = ["serde", "v4"] }
zip = "0.6.4"

[dev-dependencies]
tokio-test = "*"
