[package]
name = "mktmdbnetfetchupdate"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
flate2 = "1.0.26"
mk_lib_common = { path = "../../../src/mk_lib_common" }
mk_lib_database = { path = "../../../src/mk_lib_database" }
mk_lib_network = { path = "../../../src/mk_lib_network" }
mk_lib_rabbitmq = { path = "../../../src/mk_lib_rabbitmq" }
reqwest = { version = "0.11.18", default-features = false, features = [
    "json",
    "native-tls",
] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
sys-info = "0.9.1"
stdext = "0.3.1"
tar = "0.4.38"
tokio = { version = "1.28.2", features = ["full"] }
uuid = { version = "1.3.3", features = ["serde", "v4"] }
zip = "0.6.6"

[dev-dependencies]
tokio-test = "*"
