[package]
name = "mksharescanner"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amiquip = { version = "0.4.2", default-features = false }
chrono = { version = "0.4.23", features = ["serde"] }
ipnet="2.7.1"
reqwest = { version = "0.11.13", default-features = false, features = [
    "json",
    "native-tls",
] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.2", features = [
    "chrono",
    "json",
    "runtime-tokio-rustls",
    "postgres",
    "uuid",
] }
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.24.1", features = ["full"] }
uuid = { version = "1.2.2", features = ["serde", "v4"] }
urlencoding = "2.1.2"
walkdir = "2.3.2"

[dev-dependencies]
tokio-test = "*"
