[package]
name = "mksharescanner"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amiquip = { version = "0.4.2", default-features = false }
chrono = { version = "0.4.24", features = ["serde"] }
ipnet="2.7.2"
mk_lib_database = { path = "/root/MediaKraken/src/mk_lib_database" }
mk_lib_logging = { path = "/root/MediaKraken/src/mk_lib_logging" }
mk_lib_network = { path = "/root/MediaKraken/src/mk_lib_network" }
reqwest = { version = "0.11.17", default-features = false, features = [
    "json",
    "native-tls",
] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
stdext = "0.3.1"
sys-info = "0.9.1"
tokio = { version = "1.28.0", features = ["full"] }
uuid = { version = "1.3.2", features = ["serde", "v4"] }
walkdir = "2.3.3"

[dev-dependencies]
tokio-test = "*"
