[package]
name = "db_manufacturer_gc"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'

[dependencies]
reqwest = { version = "0.11.8", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
sqlx = { version = "0.5.9", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.4.0"
tokio = { version = "1.15.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
walkdir = "2.3.2"

[dev-dependencies]
tokio-test = "*"