[package]
name = "db_manufacturer_gc"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"

[dependencies]
mk_lib_database = { path = "/root/MediaKraken/src/mk_lib_database" }
mk_lib_network = { path = "/root/MediaKraken/src/mk_lib_network" }
# do not use rust-tls below as it's incompatible with globalcache website
reqwest = { version = "0.11.18", default-features = false, features = ["json", "native-tls"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
sqlx = { version = "0.6.3", features = [ "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.9.1"
tokio = { version = "1.28.1", features = ["full"] }
uuid = { version = "1.3.3", features = ["serde", "v4"] }

[dev-dependencies]
tokio-test = "*"
