[package]
name = "mkinotify"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
amiquip = { version = "0.4", default-features = false }
chrono = "0.4.19"
inotify = "0.9.3"
reqwest = { version = "0.11.4", default-features = false, features = ["json", "rustls-tls"] }
rustls = "0.20.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sqlx = { version = "0.5.9", features = [ "chrono", "json", "runtime-tokio-rustls", "postgres", "uuid" ] }
sys-info = "0.9.0"
tokio = { version = "1.12.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[dev-dependencies]
tokio-test = "*"