[package]
name = "mklibretrocorefetchupdate"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
crc32fast = "1.3.2"
flate2 = "1.0.26"
mk_lib_compression = { path = "/root/MediaKraken/src/mk_lib_compression" }
mk_lib_hash = { path = "/root/MediaKraken/src/mk_lib_hash" }
mk_lib_logging = { path = "/root/MediaKraken/src/mk_lib_logging" }
mk_lib_network = { path = "/root/MediaKraken/src/mk_lib_network" }
reqwest = { version = "0.11.18", default-features = false, features = ["json", "native-tls"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
stdext = "0.3.1"
sys-info = "0.9.1"
tar = "0.4.38"
tokio = { version = "1.28.2", features = ["full"] }
walkdir = "2.3.3"
uuid = { version = "1.3.3", features = ["serde", "v4"] }
zip = "0.6.6"

[dev-dependencies]
tokio-test = "*"
