[package]
name = "mklibretrocorefetchupdate"
version = "0.0.1"
edition = "2018"

[profile.release]
panic = 'abort'

[dependencies]
chrono = "0.4"
flate2 = "1.0.20"
md-5 = "0.9.1"
reqwest = { version = "0.11.3", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sys-info = "0.4.0"
tar = "0.4.37"
tokio = { version = "1.6.0", features = ["full"] }
walkdir = "2.3.2"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
zip = "0.5.13"

[dev-dependencies]
tokio-test = "*"