[package]
name = "mklibretrocorefetchupdate"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'

[dependencies]
chrono = "0.4.19"
crc32fast = "1.3.0"
flate2 = "1.0.22"
reqwest = { version = "0.11.8", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
sys-info = "0.9.1"
tar = "0.4.38"
tokio = { version = "1.15.0", features = ["full"] }
walkdir = "2.3.2"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
zip = "0.5.13"

[dev-dependencies]
tokio-test = "*"